import './bootstrap';
import '../css/app.css';
import '../css/reset.css';
import '../css/about.css';
import '../css/fond.css';
import '../css/media.css';
import '../js/script.js';
import '../js/pdf';
import '../js/pdf.worker';
import.meta.glob([ '../img/**', ]);
